version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: decido_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: n8cePEPE=_pw&a%terb~\uM27$UB7
      POSTGRES_DB: decido_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: decido_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: