"""Add session list and new statuses

Revision ID: 1352a3a25b2e
Revises: 53876f6c8830
Create Date: 2026-04-20 20:17:50.188479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1352a3a25b2e'
down_revision: Union[str, None] = '53876f6c8830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
