"""Add session list and new statuses

Revision ID: 18b1c1f7e8c2
Revises: 1352a3a25b2e
Create Date: 2026-04-20 20:20:17.127934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18b1c1f7e8c2'
down_revision: Union[str, None] = '1352a3a25b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('original_list_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['original_list_id'], ['lists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_session_lists_id'), 'session_lists', ['id'], unique=False)
    op.create_table('session_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_list_id'], ['session_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_list_items_id'), 'session_list_items', ['id'], unique=False)
    op.add_column('session_results', sa.Column('session_list_item_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_session_result', 'session_results', type_='unique')
    op.create_unique_constraint('uq_session_result', 'session_results', ['session_id', 'session_list_item_id'])
    op.drop_constraint('session_results_item_id_fkey', 'session_results', type_='foreignkey')
    op.create_foreign_key(None, 'session_results', 'session_list_items', ['session_list_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_results', 'item_id')
    op.add_column('sessions', sa.Column('original_list_id', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('countdown_duration', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('countdown_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('sessions_list_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'lists', ['original_list_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sessions', 'lobby_duration')
    op.drop_column('sessions', 'lobby_ends_at')
    op.drop_column('sessions', 'list_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('lobby_ends_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('lobby_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_list_id_fkey', 'sessions', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sessions', 'countdown_ends_at')
    op.drop_column('sessions', 'countdown_duration')
    op.drop_column('sessions', 'original_list_id')
    op.add_column('session_results', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_results', type_='foreignkey')
    op.create_foreign_key('session_results_item_id_fkey', 'session_results', 'list_items', ['item_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_session_result', 'session_results', type_='unique')
    op.create_unique_constraint('uq_session_result', 'session_results', ['session_id', 'item_id'])
    op.drop_column('session_results', 'session_list_item_id')
    op.drop_index(op.f('ix_session_list_items_id'), table_name='session_list_items')
    op.drop_table('session_list_items')
    op.drop_index(op.f('ix_session_lists_id'), table_name='session_lists')
    op.drop_table('session_lists')
    # ### end Alembic commands ###
