"""Remove original_list_id from session_lists

Revision ID: 309f9e5553a0
Revises: ca9aa6205ce2
Create Date: 2026-04-26 22:49:35.540491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '309f9e5553a0'
down_revision: Union[str, None] = 'ca9aa6205ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_lists_original_list_id_fkey', 'session_lists', type_='foreignkey')
    op.drop_column('session_lists', 'original_list_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('session_results_session_id_session_list_item_id_key', 'session_results', ['session_id', 'session_list_item_id'])
    op.create_unique_constraint('session_participants_session_id_user_id_key', 'session_participants', ['session_id', 'user_id'])
    op.add_column('session_lists', sa.Column('original_list_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('session_lists_original_list_id_fkey', 'session_lists', 'lists', ['original_list_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
