"""Update models with relationships

Revision ID: b5d240d8a16c
Revises: d435ba875d69
Create Date: 2026-03-21 21:58:01.892117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d240d8a16c'
down_revision: Union[str, None] = 'd435ba875d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('list_items_list_id_fkey', 'list_items', type_='foreignkey')
    op.create_foreign_key(None, 'list_items', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'list_items', type_='foreignkey')
    op.create_foreign_key('list_items_list_id_fkey', 'list_items', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###
