"""Add group_id to lists

Revision ID: e2966bb03c4a
Revises: 1f46bd445aac
Create Date: 2026-04-20 18:59:30.953681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2966bb03c4a'
down_revision: Union[str, None] = '1f46bd445aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('lists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'lists', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.alter_column('lists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lists', 'group_id')
    # ### end Alembic commands ###
